chore: push upstream tags on build (#45)
* chore: push upstream tags on build

* chore: linting

diff --git a/.github/workflows/daily.yml b/.github/workflows/daily.yml
--- a/.github/workflows/daily.yml
+++ b/.github/workflows/daily.yml
@@ -16,7 +16,7 @@ jobs:
           LAST_PUSHED=$(curl -s -X GET https://hub.docker.com/v2/repositories/linuxserver/smokeping/tags/latest | jq -r ".tag_last_pushed")
           if [ $(date --date "${LAST_PUSHED}" +'%s') -ge $(date --date "1 days ago" +'%s') ]; then
             echo "Upstream changed, building image"
-            echo "::set-output name=upstream::changed"
+            echo "upstream=changed" >> ${GITHUB_OUTPUT}
           else
             echo "No upstream change, skipping"
           fi
@@ -57,6 +57,27 @@ jobs:
         run: docker run --rm smokeping-speedtest:test
         if: steps.check-upstream.outputs.upstream == 'changed'
 
+      - name: Create Tags
+        id: create-tags
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          BASE_TAG_GH: "ghcr.io/${{ github.repository_owner }}/smokeping-speedtest:"
+          BASE_TAG_DOCKER: "${{ secrets.DOCKERHUB_USERNAME }}/smokeping-speedtest:"
+        run: |
+          UPSTREAM_TAGS=$(gh api \
+            -H "Accept: application/vnd.github+json" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+           /orgs/linuxserver/packages/container/smokeping/versions | jq -r '.[] | select( .metadata.container.tags | any(. == "latest") ) .metadata.container.tags | join(",")')
+          if [[ -z "${UPSTREAM_TAGS}" ]]; then
+            echo "Failed to find upstream latest tags"
+            exit 1
+          fi
+          echo "Upstream tags: ${UPSTREAM_TAGS}"
+          TAGS_GH=$(echo ${UPSTREAM_TAGS} | sed "s|[^,]*|${BASE_TAG_GH}&|g")
+          TAGS_DOCKER=$(echo ${UPSTREAM_TAGS} | sed "s|[^,]*|${BASE_TAG_DOCKER}&|g")
+          echo "tags=${TAGS_GH},${TAGS_DOCKER}" >> ${GITHUB_OUTPUT}
+        if: steps.check-upstream.outputs.upstream == 'changed'
+
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
@@ -70,6 +91,7 @@ jobs:
           registry: ghcr.io
           username: ${{ github.repository_owner }}
           password: ${{ secrets.GITHUB_TOKEN }}
+        if: steps.check-upstream.outputs.upstream == 'changed'
 
       - name: Build and push
         id: docker_build
@@ -79,8 +101,7 @@ jobs:
           file: ./Dockerfile
           push: true
           tags: |
-            ${{ secrets.DOCKERHUB_USERNAME }}/smokeping-speedtest:latest
-            ghcr.io/${{ github.repository_owner }}/smokeping-speedtest:latest
+            ${{ steps.create-tags.outputs.tags }}
           cache-from: type=local,src=/tmp/.buildx-cache
           cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
         if: steps.check-upstream.outputs.upstream == 'changed'
